### PR TITLE
Clarify All Dungeon goal.

### PR DESCRIPTION
**Pull request by TarThoron**

### CODE REVIEW

**Comment by RebelusQuo** [comment]
👍 , but see review comment.

**Comment by TarThoron** [comment]
I don't see any review comments.

**Comment by RebelusQuo** [comment]
Under the "Files changed" tab in the code, or right here in the conversation under your single commit entry in the timeline.

**Comment by TarThoron** [comment]
Screenshot_20220726-151102
Screenshot_20220726-151029
Screenshot_20220726-151042

**Comment by RebelusQuo** [comment]
Giant screenshots, but ok, I think I have to assign you as reviewer which I on the other hand can not do. Thanks github. This is especially irritating since all I wanted to say, using fancy toys, was that you have a typo. It's "acquired", an extra C.

**Review by dnevill — COMMENTED** [review]
This is just a sneaky test to see if all review comments are secret squirrel comments or just Regulus's.

Also "acquired" is spelled with a 'c'.

**Comment by dnevill** [comment]
Out of curiosity does my reviewer comment show up for you Tar or is it just Rebelus who gets to make SECRET REVIEWS?

**Comment by RebelusQuo** [comment]
@dnevill Thank you for providing a "unit test" _awaiting the test outcome with much excitement_

**Comment by TarThoron** [comment]
I see dnevill under Reviewers. "Still in progress?"

Thought "aquired" looked odd, but spell check didn't flag it. Guess it's disabled in that field.

**Review by RebelusQuo — APPROVED** [review]

**Comment by RebelusQuo** [comment]
Wait.. I thought I approved the.. um.. the correct changes, not my "pointing out" review comment.. This is all very confusing..

**Review by dnevill — APPROVED** [review]
I approve of these comments and/or commits.

**Comment by RebelusQuo** [comment]
Never before has such a small contribution been so thoroughly reviewed as on this occasion. Good job guys!

**Pull request merged**
