### PR TITLE
Sanitize seed input

### PR DESCRIPTION
**Pull request by avvie**
until now webRando returned 500 if you input a non number seed.
Those seeds are written directly to the database. 
So I sanitized the input in RandomizerController.cs 
added a couple of lines of logic for the generation on the SMZ3 and SM side to handle the strings

### CODE REVIEW

**Comment by RebelusQuo** [comment]
```
var seed = "123";
var expected = int.Parse(seed);
var actual = seed.ToCharArray().Sum(x => x);
Console.Write(actual == expected); // False
```

**Comment by RebelusQuo** [comment]
Also, looking at the implementation, I only see data being persisted at line 84. the seed number should fail parsing and throw an exception before that. Are you positive records are being stored in the database?

**Comment by avvie** [comment]
image

Actual is not expected math wise. that is true. But the SM rando does a similar thing for tournament seeds, where it takes the seed and uses it as the seed to the RNG to create a seed to use for the tournament. Makes sense as it obfuscates the seed. 

In essense though it does give you the opportunity to have fun with the seeds. A "complaint" i had from couple of close friends that wanted to be able to write a message as a seed. But that would crash the thing and throw an exception. That would also protect from writing any unsanitary things to the db. 

Random seeds will work the same as they do know. Although seeding with a number will be different from a previous version to my change, it is not the case that it changes quality of a seed in any way. 
I do see the problem of having seed 00001 and 10000 be the same seed. I will think it over a bit.

Does it make sense to you to check if there is alphanumeric characters in the string and then and only then to do 
`var actual = seed.ToCharArray().Sum(x => x);`

or is it something that is not of interest in general?

**Comment by RebelusQuo** [comment]
My unit test like demonstration was just to point out the obvious issue of not respecting the API. The further issue, and even more severe, is that you shrink the seed number domain from [0, 2^32) to [0, 570], non-continuous (assuming digit input in ascii). or in other words, 00001 and 10000 being the same seed is a huge problem.

**Comment by RebelusQuo** [comment]
Now, on the input sanitizing, that's worth it of course. But it should probably check for not legal characters, rather than illegal characters, so drop request on first `[^\d]` in the seed string.

**Comment by avvie** [comment]
although this will happen in the weekend. I will do input sanitization.
and I can treat a string as a base 52 number that would solve the domain reduction problem, will play around with it and come back

**Comment by avvie** [comment]
So instead of messing with the controller that much. I handled the input sanitization on the react side. 

If you input a character in the seed box, it will produce an alert (I am incompetent when it comes to UI), that will inform the user what is going on.

**Pull request closed without merging**
